#!/usr/bin/env bash
#Script to list content of current directory where only the part of the name after the first dash is displayed

files="$(ls)"

for f in $files;
do
	echo "$f" | cut -d "-" -f2
done
